### PR TITLE
Added utils function for 0-transparent cmaps

### PR DESCRIPTION
**Pull request by timtreis**
Note: the only existing utils function was using a different testing pattern, which I now aligned with the usual one. But therefore there's an additonal image in this PR

### CODE REVIEW

**Comment by LucaMarconato** [comment]
Amazing! Ready for review?

**Comment by timtreis** [comment]
Added the function @LucaMarconato @giovp. Probably best to add it to one of the notebooks to illustrate usage - which one do you think would be best?

**Comment by LucaMarconato** [comment]
Thanks! I am working on the Visium HD notebook right now, so I can add it there 😊

**Review by melonora — APPROVED** [review]
LGTM! Maybe one consideration is to add a parameter that automatically does this for the user e,g, `zero_transparent`, but this could be added in a different PR. Also this PR does make it a bit more difficult for view configurations as we are dealing with different alpha values. May have to think of serialization of the colormap values.

**Comment by timtreis** [comment]
Yeah, based on https://github.com/scverse/spatialdata-plot/issues/242 we decided not to include it as an argument but like this. But I agree, eventually, we should probably just serialise the data. I think ggplot f.e. also does it like this when generating the plot

**Pull request merged**
